# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"timecode": "00_utils.ipynb",
         "print_device_info": "00_utils.ipynb",
         "dump_tensors": "00_utils.ipynb",
         "Monitor": "00_utils.ipynb",
         "show_gpu": "00_utils.ipynb",
         "round_t": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://puzzler10.github.io/travis_attack/"

git_url = "https://github.com/puzzler10/travis_attack/tree/main/"

def custom_doc_links(name): return None
