# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"set_seed": "00_utils.ipynb",
         "set_session_options": "00_utils.ipynb",
         "prepare_logger": "00_utils.ipynb",
         "timecode": "00_utils.ipynb",
         "print_device_info": "00_utils.ipynb",
         "dump_tensors": "00_utils.ipynb",
         "Monitor": "00_utils.ipynb",
         "show_gpu": "00_utils.ipynb",
         "round_t": "00_utils.ipynb",
         "merge_dicts": "00_utils.ipynb",
         "display_all": "00_utils.ipynb",
         "unpack_nested_lists_in_df": "00_utils.ipynb",
         "robust_rmtree": "00_utils.ipynb",
         "table2df": "00_utils.ipynb",
         "check_no_nans_or_infs": "02_tests.ipynb",
         "Config": "03_config.ipynb",
         "prepare_models": "07_models.ipynb",
         "pp_model_freeze_layers": "07_models.ipynb",
         "save_pp_model": "07_models.ipynb",
         "resume_pp_model": "07_models.ipynb",
         "get_vm_probs": "07_models.ipynb",
         "get_optimizer": "07_models.ipynb",
         "get_start_end_special_token_ids": "07_models.ipynb",
         "ProcessedDataset": "10_data.ipynb",
         "Trainer": "20_trainer.ipynb",
         "print_info_on_generated_text": "30_logging.ipynb",
         "check_parameters_update": "30_logging.ipynb",
         "plot_grad_flow": "35_charts.ipynb",
         "plot_examples_chart": "35_charts.ipynb"}

modules = ["utils.py",
           "tests.py",
           "config.py",
           "models.py",
           "data.py",
           "trainer.py",
           "logging.py",
           "charts.py"]

doc_url = "https://puzzler10.github.io/travis_attack/"

git_url = "https://github.com/puzzler10/travis_attack/tree/main/"

def custom_doc_links(name): return None
