# AUTOGENERATED! DO NOT EDIT! File to edit: 02_tests.ipynb (unless otherwise specified).

__all__ = ['check_no_nans_or_infs']

# Cell
import torch

# Cell
def check_no_nans_or_infs(x):
    assert torch.all(~torch.isnan(x))
    assert torch.all(~torch.isneginf(x))
    assert torch.all(~torch.isposinf(x))