wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: huggingface
    huggingface_version: 4.5.0
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.5
    start_time: 1635382215
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      4: 3.8.5
      5: 0.12.6
      6: 4.5.0
      8:
      - 1
      - 2
      - 5
